version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATA_DIR: /app/app/data
      SCHEMAS_DIR: /app/app/schemas
      SEEDS_DIR: /app/app/seeds
    volumes:
      - ./app:/app/app
